# View pre-commit hooks at https://github.com/pre-commit/pre-commit-hooks#hooks-available
# !!!RUN pre-commit autoupdate!!! To get the latest versions. This gist has been collecting dust bunnies and cob webs.
# The commented repos/hooks will NOT autoupdate! If you're going to use them, uncomment and run pre-commit autoupdate.

default_stages: [commit, push]

fail_fast: false

minimum_pre_commit_version: '1.15.0'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
    -   id: pretty-format-json
        args:
          - --autofix
          - --indent=4
          - --no-ensure-ascii
          - --no-sort-keys
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]  # Preserve Markdown hard linebreaks

-   repo: local
    hooks:
    - id: autoflake
      name: autoflake
      entry: bash -c 'cd hasher && exec poetry run autoflake .'
      language: system
      types: [ python ]
      args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]

    - id: flake8p
      name: Check with Flake8p
      entry: bash -c 'cd hasher && exec poetry run flake8p'

      language: system
      pass_filenames: false
      types: [ python ]
      args: [ --count, . ]

    # Docformatter https://pypi.org/project/docformatter/
-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args:
          - --in-place
          - -r
          - --blank
          - --recursive
          - --wrap-summaries=72
          - --wrap-descriptions=72
          - --pre-summary-newline
          - --make-summary-multi-line

    # Add trailing commas https://github.com/asottile/add-trailing-comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma

    # iSort https://pycqa.github.io/isort/
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args:
          - --trailing-comma
          - --use-parentheses
          - --balanced
          - --py=38
          - --profile=black
          - -l=120

    # Black https://black.readthedocs.io/en/stable/
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args:
          - --target-version=py38
          - --line-length=120

    # Removes unused variables and imports https://github.com/myint/autoflake
#-   repo: https://github.com/myint/autoflake
#    rev: v1.4
#    hooks:
#      - id: autoflake
#        args:
#          - --in-place
#          - --remove-unused-variables
#          - --remove-all-unused-imports

    # Flake8 https://flake8.pycqa.org/en/latest/index.html#
#-   repo: https://gitlab.com/pycqa/flake8
#    rev: 3.9.2
#    hooks:
#    -   id: flake8
#        exclude: description.py
#        additional_dependencies: [
#          pep8-naming,
#]
#        args:
#          - --doctests
#          - --max-line-length=120

    # Unimport https://unimport.hakancelik.dev/#/
#-   repo: https://github.com/hakancelik96/unimport
#    rev: 0.10.0
#    hooks:
#    -   id: unimport
#        args:
#          - --remove
#          - --requirements
#          - --include-star-import
#          - --gitignore

    # Pyupgrade https://github.com/asottile/pyupgrade
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
    -   id: pyupgrade

    # Interrogate https://interrogate.readthedocs.io/en/latest/
    # Checks percentage of code coverage. Change --fail-under to update.
#-   repo: https://github.com/econchick/interrogate
#    rev: 1.5.0
#    hooks:
#    -   id: interrogate
#        args:
#          - --fail-under=95
#          - --verbose
#          - --ignore-init-method
#          - --ignore-init-module
